debian_packages: [nginx=1.22.0-1ubuntu1.1, ufw=0.36.1-4build1, cowsay=3.03+dfsg2-8]
redhat_packages: [epel-release, nginx-1.20.1, firewalld-0.6.3, cowsay-3.04]
redhat_packages_to_check: [nginx, firewalld]
ufw_ports: [22, 80, 443, 8080]
nginx_ports: [80, 8080]
connection_number: 768
log_dir: /var/log/nginx
fqdn: hopetoknow.com
