debian_packages: [nginx=1.22.0-1ubuntu1.1, ufw=0.36.1-4build1, cowsay=3.03+dfsg2-8]
redhat_packages: [epel-release, nginx-1.20.1, firewalld-0.6.3, cowsay-3.04]
redhat_packages_to_check: [nginx, firewalld]
redhat_directories_to_create: [/var/www/html, /etc/nginx/sites-available, /etc/nginx/sites-enabled]
ufw_ports: [22, 80, 443, 8080]
nginx_ports: [80, 8080]
nginx_user: "{{ 'www-data' if ansible_os_family == 'Debian' else 'nginx' }}"
log_dir: /var/log/nginx
connection_number: 768
fqdn: hopetoknow.com
