- name: Install and configure nginx
  hosts: webservers
  become: yes
  vars:
    nginx_port: 8080
    server_presentation: "This is server {{ ansible_hostname }}!"
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest

    - name: Copy index.html
      ansible.builtin.template:
        src: "{{ root_dir }}/index.html.j2"
        dest: /usr/share/nginx/html/index.html

    - name: Copy configuration file
      ansible.builtin.template:
        src: "{{ root_dir }}/nginx.conf.j2"
        dest: /etc/nginx/nginx.conf
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
        