- name: Install and configure nginx, install cowsay
  hosts: webservers
  become: yes
  vars:
    nginx_port: 8080
    server_presentation: "This is server {{ ansible_hostname }}!"
    packages: [nginx=1.22.0-1ubuntu1.1, ufw=0.36.1-4build1, cowsay=3.03+dfsg2-8]
    ports: [22, 443, 8080]
  tasks:
    - name: Install nginx, UFW and cowsay packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ packages }}"

    - name: Make the cow say hostname
      ansible.builtin.command: cowsay "I am server {{ ansible_hostname }}"
      register: cowsay_output

    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Allow traffic
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop: "{{ ports }}"

    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - name: Copy nginx configuration file
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Reload nginx

    - name: Copy index.html
      ansible.builtin.template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html

  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
        