- name: Install soft
  hosts: webservers
  become: true
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
  roles:
    - role: geerlingguy.git
    - role: geerlingguy.java
    - role: gantsign.maven
  tasks:
    - name: Install Make
      ansible.builtin.apt:
        name: make
        state: present
